#' Estimation Parameters Using dropsim
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param verbose Whether to return messages or not
#'
#' @references Github URL: <https://github.com/marchinilab/dropsim>
#'
dropsim_estimation <- function(SCST_Object,
                               verbose = FALSE
){
  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("dropsim", quietly = TRUE)){
    message("dropsim is not installed on your device...")
    message("Installing dropsim...")
    devtools::install_github("marchinilab/dropsim")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  ref_data <- as.matrix(SCST_Object@reference)
  seed <- SCST_Object@seed
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using dropsim")
  }
  # Seed
  set.seed(seed)
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- dropsim::fit_parameters(ref_data, plot = FALSE)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("dropsim" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                       "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("dropsim" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("dropsim" = NULL)
  return(SCST_Object)
}



#' Simulate ScRNA-seq Data Using dropsim
#'
#' @param estimated_result The SCST object after estimating parameters using [splatter::zinbwave_estimation()]
#' @param cell_num The expected number of simulated cells. If NULL, the original cell number in the reference data will be adopted.
#' @param gene_num The expected number of simulated genes. If NULL, the original gene number in the reference data will be adopted.
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#'
dropsim_simulation <- function(estimated_result,
                               cell_num = NULL,
                               gene_num = NULL,
                               return_format,
                               verbose = FALSE,
                               seed
){
  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("dropsim", quietly = TRUE)){
    message("dropsim is not installed on your device...")
    message("Installing dropsim...")
    devtools::install_github("marchinilab/dropsim")
  }
  parameters <- estimated_result@estimation_result$dropsim
  if(!is.null(cell_num)){
    methods::slot(parameters, "n_cells") <- as.integer(cell_num)
  }
  if(!is.null(gene_num)){
    methods::slot(parameters, "n_genes") <- as.integer(gene_num)
  }
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using dropsim")
  }
  # Simulation
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- dropsim::simulateDGE(parameters = parameters,
                                            seed = seed)
  )
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- as.matrix(simulate_result[["counts"]])
  ## colnames rownames
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(counts),
                         row.names = colnames(counts))
  ## row data
  row_data <- data.frame("gene_name" = rownames(counts),
                         row.names = rownames(counts))
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)

  simulate_result <- data_conversion(SCE_object = simulate_result, return_format = return_format)
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("dropsim" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                            "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("dropsim" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("dropsim" = parameters)
  return(estimated_result)
}
