#' Estimation Parameters Using dyntoy
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param verbose Whether to return messages or not
#'
#' @export
#'

dyntoy_estimation <- function(SCST_Object,
                              verbose = FALSE){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!requireNamespace("tislingshot", quietly = TRUE)){
    message("tislingshot is not installed on your device...")
    message("Installing tislingshot...")
    devtools::install_github("dynverse/ti_slingshot/package/")
  }
  if(!requireNamespace("NbClust", quietly = TRUE)){
    message("NbClust is not installed on your device...")
    message("Installing NbClust...")
    utils::install.packages("NbClust")
  }
  ref_data <- as.matrix(SCST_Object@reference)
  seed <- SCST_Object@seed
  group_label <- SCST_Object@group_label
  if(S4Vectors::isEmpty(group_label)){
    message("Performing k-means and determin the best number of clusters...")
    clust <- NbClust::NbClust(data = t(ref_data),
                              distance = 'euclidean',
                              min.nc = 2,
                              max.nc = sqrt(nrow(t(ref_data))),
                              method = "kmeans",
                              index = "dunn")
    group_label <- paste0("Group", clust[["Best.partition"]])
  }
  ref_data <- dynwrap::wrap_expression(counts = t(ref_data),
                                       expression = log2(t(ref_data) + 1))
  ## Add group
  if(verbose){
    message("Add grouping to data...")
  }
  ref_data <- dynwrap::add_grouping(dataset = ref_data,
                                    grouping = group_label)
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using dyntoy")
  }
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- dynwrap::infer_trajectory(dataset = ref_data,
                                                 method = tislingshot::ti_slingshot(),
                                                 parameters = NULL,
                                                 give_priors = NULL,
                                                 seed = seed,
                                                 verbose = verbose)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("dyntoy" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                      "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("dyntoy" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("dyntoy" = NULL)
  return(SCST_Object)
}


#' Simulate ScRNA-seq Data Using dyntoy
#'
#' @param estimated_result The SCST object after estimating parameters using [SCST::dyntoy_estimation()]
#' @param cell_num The expected number of simulated cells. If NULL, the original cell number in the reference data will be adopted.
#' @param gene_num The expected number of simulated genes. If NULL, the original gene number in the reference data will be adopted.
#' @param de_prop The proportion of DEGs over all genes between different simulated cell groups. Default is 0.2.
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#' @param ... Other parameters represented in dyntoy, see [dyntoy::generate_dataset()]
#'
dyntoy_simulation <- function(estimated_result,
                              cell_num = NULL,
                              gene_num = NULL,
                              de_prop = 0.2,
                              return_format,
                              verbose = FALSE,
                              seed,
                              ...
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("dyntoy", quietly = TRUE)){
    message("dyntoy is not installed on your device")
    message("Installing dyntoy...")
    devtools::install_github("dynverse/dyntoy")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  existed_params <- list(
    "model" = estimated_result@estimation_result$dyntoy$trajectory_type,
    "differentially_expressed_rate" = de_prop
  )
  # cell_num
  if(!is.null(cell_num)){
    existed_params[["num_cells"]] <- cell_num
  }else{
    existed_params[["num_cells"]] <- estimated_result@cell_num
  }
  # nGenes
  if(!is.null(gene_num)){
    existed_params[["num_features"]] <- gene_num
  }else{
    existed_params[["num_features"]] <- estimated_result@gene_num
  }
  ext_argument <- list(...)
  argument <- formals(dyntoy::generate_dataset)
  used_argument <- change_parameters(existed_params, argument)
  used_argument <- used_argument[-grep("sample_mean_count", names(used_argument))]
  used_argument <- used_argument[-grep("sample_dispersion_count", names(used_argument))]
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using dyntoy")
  }
  # Seed
  set.seed(seed)
  # Estimation
  assign("map_dbl", dynutils::mapdf_dbl)
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- do.call(dyntoy::generate_dataset, used_argument)
  )
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  de_gene <- simulate_result[["tde_overall"]][["differentially_expressed"]]
  simulate_result <- t(as.matrix(simulate_result[["counts"]]))
  colnames(simulate_result) <- paste0("Cell", 1:ncol(simulate_result))
  rownames(simulate_result) <- paste0("Gene", 1:nrow(simulate_result))
  ## col_data
  col_data <- data.frame("cell_name" = colnames(simulate_result),
                         row.names = colnames(simulate_result))
  ## row_data
  row_data <- data.frame("gene_name" = rownames(simulate_result),
                         "de_gene" = ifelse(de_gene, "yes", "no"),
                         row.names = rownames(simulate_result))
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = simulate_result),
                                                                colData = col_data,
                                                                rowData = row_data)
  simulate_result <- data_conversion(SCE_object = simulate_result, return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("dyntoy" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                           "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("dyntoy" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("dyntoy" = used_argument)
  return(estimated_result)
}
