#' Estimation Parameters Using Lun2
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param min.size Minimum size of clusters when identifying group of cells in the data.
#' @param verbose Whether to return messages or not
#' @param ... Other parameters represented in Lun2, see [splatter::lun2Estimate()]
#'

Lun2_estimation <- function(SCST_Object,
                            min.size = 50,
                            verbose = FALSE,
                            ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  ref_data <- SCST_Object@reference %>% as.matrix()
  seed <- SCST_Object@seed
  plates <- SCST_Object@batch_label
  existed_params <- list("counts" = ref_data,
                         "plates" = as.numeric(as.factor(plates)),
                         "min.size" = min.size,
                         "verbose" = verbose)
  existed_params <- append(existed_params, list(...))
  argument <- formals(splatter::lun2Estimate)
  used_argument <- change_parameters(existed_params, argument)
  used_argument <- used_argument[-grep("params", names(used_argument))]
  used_argument <- used_argument[-grep("BPPARAM", names(used_argument))]
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using Lun2")
  }
  # Seed
  set.seed(seed)
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- do.call(splatter::lun2Estimate, used_argument)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("Lun2" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                    "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("Lun2" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("Lun2" = used_argument[-1])
  return(SCST_Object)
}



#' Simulate ScRNA-seq Data Using Lun2
#'
#' @param estimated_result The SCST object after estimating parameters using [splatter::Lun2_estimation()]
#' @param cell_num The expected number of simulated cells. If NULL, the original cell number in the reference data will be adopted.
#' @param gene_num The expected number of simulated genes. If NULL, the original gene number in the reference data will be adopted.
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#' @param ... Other parameters represented in Lun2, see [splatter::Lun2Params()]
#'
Lun2_simulation <- function(estimated_result,
                            cell_num = NULL,
                            gene_num = NULL,
                            return_format,
                            verbose = FALSE,
                            seed,
                            ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  parameters <- estimated_result@estimation_result$Lun2
  # cell_num
  if(!is.null(cell_num)){
   cell.plates.prop <-  as.numeric(table(parameters@cell.plates))/estimated_result@cell_num
   cell.plates <- proportionate(number = cell_num,
                                result_sum_strict = cell_num,
                                prop = cell.plates.prop,
                                prop_sum_strict = 1)
   cell.plates <- as.factor(cell.plates)
  }else{
    cell.plates <- parameters@cell.plates
  }
  # nGenes
  if(is.null(gene_num)){
    gene_num <- estimated_result@gene_num
  }
  existed_params <- list("cell.plates" = cell.plates,
                         "nGenes" = gene_num,
                         "seed" = seed,
                         "de.nGenes" = round(gene_num * 0.2))
  existed_params <- append(existed_params, list(...))
  used_argument <- change_parameters(parameters, existed_params)
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using Lun2")
  }
  # Simulation
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- splatter::lun2Simulate(used_argument,
                                              verbose = verbose,
                                              zinb = TRUE)
  )
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  # counts
  counts <- as.matrix(SingleCellExperiment::counts(simulate_result))
  # col_data
  col_data <- as.data.frame(SummarizedExperiment::colData(simulate_result))
  if(used_argument@de.nGenes == 0){
    col_data <- col_data[, c("Cell", "Plate")]
    colnames(col_data) <- c("cell_name", "batch")
  }else{
    col_data <- col_data[, c("Cell", "Plate", "Ingroup")]
    colnames(col_data) <- c("cell_name", "batch", "ingroup")
  }

  # row_data
  if(used_argument@de.fc == 0){
    row_data <- data.frame("gene_name" = paste0("Gene", 1:nrow(counts)),
                           row.names = rownames(counts))
  }else{
    row_data <- as.data.frame(SummarizedExperiment::rowData(simulate_result))
    group_fac <- row_data[, grep(colnames(row_data), pattern = "^DEFac")]
    total_sum <- rowSums(group_fac)
    de_gene <- ifelse(total_sum == 2, "no", "yes")
    row_data[, 2] <- de_gene
    row_data <- row_data[, 1:2]
    row_data <- BiocGenerics::cbind(row_data, group_fac)
    colnames(row_data) <- c("gene_name", "de_gene", colnames(group_fac))
  }

  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)
  simulate_result <- data_conversion(SCE_object = simulate_result, return_format = return_format)
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("Lun2" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                         "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("Lun2" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("Lun2" = used_argument)
  return(estimated_result)
}
