#' Estimation Parameters Using SRTsim
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param sim_schem A character string specifying simulation scheme. "tissue" stands for tissue-based simulation; "domain" stands for domain-specific simulation. Default is "domain".
#' @param marginal Specification of the types of marginal distribution ("auto_choose", "zinb", "nb", "poisson", "zip")
#' @param verbose Whether to return messages or not
#' @param ... Other parameters represented in SRTsim, see [SRTsim::srtsim_fit()]
#'
#' @importFrom checkmate check_choice
#' @importFrom utils install.packages
#' @importFrom peakRAM peakRAM
#' @importFrom methods slot slot<- is
#' @importFrom S4Vectors isEmpty
#'
#' @export
#'
#' @references Zhu J, Shang L, Zhou X. SRTsim: spatial pattern preserving simulations for spatially resolved transcriptomics[J]. Genome Biology, 2023, 24(1): 39.
#'
SRTsim_estimation <- function(SCST_Object,
                              sim_schem = "domain",
                              marginal = "auto_choose",
                              verbose = FALSE,
                              ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!requireNamespace("SRTsim")){
    message("Installing SRTsim ...")
    utils::install.packages("SRTsim")
  }
  ref_data <- methods::slot(SCST_Object, "reference")
  group_label <- methods::slot(SCST_Object, "group_label")
  spatial_x <- methods::slot(SCST_Object, "spatial_x")
  spatial_y <- methods::slot(SCST_Object, "spatial_y")
  if(S4Vectors::isEmpty(spatial_x) | S4Vectors::isEmpty(spatial_y)){
    stop("Please input the coordinate values of cells/spots on the x- or y-axis in ST data")
  }
  seed <- methods::slot(SCST_Object, "seed")
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  ### scheme
  checkmate::check_choice(x = sim_schem, choices = c("tissue", "domain"))
  ### marginal
  checkmate::check_choice(x = marginal, choices = c("auto_choose", "zinb", "nb", "poisson", "zip"))
  ### group_info
  if(S4Vectors::isEmpty(group_label)){
    group_label <- rep("A", ncol(ref_data))
  }
  ## create a SRT object
  metadata <- data.frame("x" = spatial_x,
                         "y" = spatial_y,
                         "label" = group_label)
  rownames(metadata) <- colnames(ref_data)
  simSRT <- SRTsim::createSRT(count_in = ref_data,
                              loc_in = metadata)

  # External parameters
  ext_argument <- list(...)
  argument <- formals(SRTsim::srtsim_fit)
  used_argument <- change_parameters(ext_argument, argument)
  used_argument[["simsrt"]] <- simSRT
  used_argument[["sim_scheme"]] <- sim_schem
  used_argument[["marginal"]] <- marginal

  # Seed
  set.seed(seed)
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- do.call(SRTsim::srtsim_fit, used_argument)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("SRTsim" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                      "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("SRTsim" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("SRTsim" = used_argument[-1])
  return(SCST_Object)
}




#' Simulate ST Data Using SRTsim
#'
#' @param estimated_result The SCST object after estimating parameters using [SCST::SRTsim_estimation()]
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#' @param ... Other parameters represented in SRTsim, see [SRTsim::srtsim_count()]
#'
#' @export
#'
#' @references Zhu J, Shang L, Zhou X. SRTsim: spatial pattern preserving simulations for spatially resolved transcriptomics[J]. Genome Biology, 2023, 24(1): 39.
#'
SRTsim_simulation <- function(estimated_result,
                              verbose = FALSE,
                              seed,
                              return_format,
                              ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  if(!requireNamespace("SRTsim")){
    message("Installing SRTsim ...")
    utils::install.packages("SRTsim")
  }
  if(methods::is(estimated_result, "SCST")){
    input <- estimated_result@estimation_result$SRTsim
  }else{
    stop("Please input the estimated result which is a SCST object")
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using SRTsim")
  }

  # External parameters
  ext_argument <- list(...)
  argument <- formals(SRTsim::srtsim_count)
  used_argument <- change_parameters(ext_argument, argument)
  used_argument[["verbose"]] <- verbose
  used_argument[["simsrt"]] <- input
  used_argument[["nn_func"]] <- "mean"
  # Seed
  set.seed(seed)
  # Estimation
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- do.call(SRTsim::srtsim_count, used_argument)
  )
  used_argument[["seed"]] <- seed
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  # counts
  counts <- methods::as(simulate_result@simCounts, "dgCMatrix")
  # col_data
  col_data <- as.data.frame(simulate_result@simcolData)
  colnames(col_data) <- c("spatial_x", "spatial_y", "group")
  col_data$"cell_name" <- rownames(col_data)
  # row_data
  row_data <- data.frame("gene_name" = rownames(counts))
  rownames(row_data) <- rownames(counts)

  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)
  simulate_result <- data_conversion(SCE_object = simulate_result,
                                     return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("SRTsim" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                           "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("SRTsim" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("SRTsim" = used_argument[-1])
  return(estimated_result)
}
