#' Estimation Parameters Using VeloSim
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param verbose Whether to return messages or not
#'
#' @export
#' @references Zhang Z, Zhang X. VeloSim: Simulating single cell gene-expression and RNA velocity. BioRxiv, 2021. <https://doi.org/10.1101/2021.01.11.426277>
#'
VeloSim_estimation <- function(SCST_Object,
                               verbose = FALSE
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("VeloSim", quietly = TRUE)){
    message("VeloSim is not installed on your device")
    message("Installing VeloSim...")
    devtools::install_github("PeterZZQ/VeloSim")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  ref_data <- SCST_Object@reference
  if(!S4Vectors::isEmpty(SCST_Object@group_label)){
    group <- SCST_Object@group_label
  }else{
    group <- NULL
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using VeloSim")
  }
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- .make_trees(ref_data = ref_data,
                                   group = group,
                                   is_Newick = FALSE,
                                   is_parenthetic = FALSE)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("VeloSim" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                       "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("VeloSim" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("VeloSim" = NULL)
  return(SCST_Object)
}



#' Simulate ScRNA-seq Data Using VeloSim
#'
#' @param estimated_result The SCST object after estimating parameters by [SCST::VeloSim_estimation()].
#' @param cell_num The expected number of simulated cells. If NULL, the original cell number in the reference data will be adopted.
#' @param gene_num The expected number of simulated genes. If NULL, the original gene number in the reference data will be adopted.
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#' @param ... Other parameters represented in VeloSim, see [VeloSim::SimulateVeloTree()]
#'
#'
#' @references Zhang Z, Zhang X. VeloSim: Simulating single cell gene-expression and RNA velocity. BioRxiv, 2021. <https://doi.org/10.1101/2021.01.11.426277>
#'
VeloSim_simulation <- function(estimated_result,
                               cell_num = NULL,
                               gene_num = NULL,
                               return_format,
                               verbose = FALSE,
                               seed,
                               ...
){

  ##############################################################################
  ####                            Environment                                ###
  ##############################################################################
  if(!requireNamespace("VeloSim", quietly = TRUE)){
    message("VeloSim is not installed on your device")
    message("Installing VeloSim...")
    devtools::install_github("PeterZZQ/VeloSim")
  }
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  existed_params <- list(
    "phyla" = estimated_result@estimation_result$VeloSim,
    "randseed" = seed
  )
  # cell_num
  if(!is.null(cell_num)){
    existed_params[["ncells_total"]] <- cell_num
  }else{
    existed_params[["ncells_total"]] <- estimated_result@cell_num
  }
  # nGenes
  if(!is.null(gene_num)){
    existed_params[["ngenes"]] <- gene_num
  }else{
    existed_params[["ngenes"]] <- estimated_result@gene_num
  }
  ext_argument <- list(...)
  argument <- formals(VeloSim::SimulateVeloTree)
  used_argument <- change_parameters(existed_params, argument)
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using VeloSim")
  }
  used_argument[["ncells_total"]] <- used_argument[["ncells_total"]] + 2
  # Estimation
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- do.call(VeloSim::SimulateVeloTree, used_argument)
  )
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  counts <- simulate_result[["counts_s"]]
  colnames(counts) <- paste0("Cell", 1:ncol(counts))
  rownames(counts) <- paste0("Gene", 1:nrow(counts))
  ## col_data
  group <- as.numeric(as.factor(simulate_result[["backbone"]]))
  col_data <- data.frame("cell_name" = colnames(counts),
                         "group" = paste0("Group", group),
                         row.names = colnames(counts))
  ## row_data
  row_data <- data.frame("gene_name" = rownames(counts),
                         row.names = rownames(counts))
  # Establish SingleCellExperiment
  simulate_result <- SingleCellExperiment::SingleCellExperiment(list(counts = counts),
                                                                colData = col_data,
                                                                rowData = row_data)
  simulate_result <- data_conversion(SCE_object = simulate_result, return_format = return_format)

  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("VeloSim" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                            "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("VeloSim" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("VeloSim" = used_argument)
  return(estimated_result)
}
