#' Estimation Parameters Using ZINB-WaVE
#'
#' @param SCST_Object A SCST object generated by [SCST::Create_SCST_Object()]
#' @param verbose Whether to return messages or not
#' @param ... Other parameters represented in ZINB-WaVE, see [splatter::ZINBParams()]
#'
#' @importFrom stats model.matrix
#'
#' @export
#'

zinbwave_estimation <- function(SCST_Object,
                                verbose = FALSE,
                                ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  ref_data <- as.matrix(SCST_Object@reference)
  seed <- SCST_Object@seed
  existed_params <- list("counts" = ref_data)
  existed_params <- append(existed_params, list(...))
  argument <- formals(splatter::zinbEstimate)
  used_argument <- change_parameters(existed_params, argument)
  used_argument <- used_argument[-grep("params", names(used_argument))]
  used_argument <- used_argument[-grep("BPPARAM", names(used_argument))]
  used_argument <- used_argument[-length(used_argument)]
  if(!S4Vectors::isEmpty(SCST_Object@group_label)){
    group <- SCST_Object@group_label
    if(!S4Vectors::isEmpty(SCST_Object@batch_label)){
      batch <- SCST_Object@batch_label
      used_argument$design.samples <- stats::model.matrix(~group + batch)
    }else{
      used_argument$design.samples <- stats::model.matrix(~group)
    }
  }else{
    if(!S4Vectors::isEmpty(SCST_Object@batch_label)){
      batch <- SCST_Object@batch_label
      used_argument$design.samples <- stats::model.matrix(~batch)
    }
  }
  ##############################################################################
  ####                            Estimation                                 ###
  ##############################################################################
  if(verbose){
    message("Estimating parameters using ZINB-WaVE")
  }
  # Seed
  set.seed(seed)
  # Estimation
  estimate_detection <- peakRAM::peakRAM(
    estimate_result <- do.call(splatter::zinbEstimate, used_argument)
  )
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(SCST_Object, "estimation_time_memory") <- list("zinbwave" = list("estimation_time" = estimate_detection$Elapsed_Time_sec,
                                                                        "estimation_memory" = estimate_detection$Peak_RAM_Used_MiB))
  slot(SCST_Object, "estimation_result") <- list("zinbwave" = estimate_result)
  slot(SCST_Object, "estimation_parameters") <- list("zinbwave" = used_argument[-1])
  return(SCST_Object)
}


#' Simulate ScRNA-seq Data Using ZINB-WaVE
#'
#' @param estimated_result The SCST object after estimating parameters using [splatter::zinbwave_estimation()]
#' @param verbose Whether to return messages or not
#' @param seed Random seed
#' @param return_format The format of returned simulation data. Choices: list, SingleCellExperiment and Seurat.
#' @param ... Other parameters represented in ZINB-WaVE, see [splatter::zinbSimulate()]
#'
#' @export
#'
zinbwave_simulation <- function(estimated_result,
                                return_format,
                                verbose = FALSE,
                                seed,
                                ...
){
  ##############################################################################
  ####                               Check                                   ###
  ##############################################################################
  parameters <- estimated_result@estimation_result$zinbwave
  # Seed
  parameters <- splatter::setParam(parameters, name = "seed", value = seed)
  ##############################################################################
  ####                            Simulation                                 ###
  ##############################################################################
  if(verbose){
    message("Simulating datasets using zinbwave")
  }
  # Simulation
  simulate_detection <- peakRAM::peakRAM(
    simulate_result <- splatter::zinbSimulate(parameters, verbose = verbose)
  )
  ##############################################################################
  ####                        Format Conversion                              ###
  ##############################################################################
  simulate_result <- data_conversion(SCE_object = simulate_result, return_format = return_format)
  ##############################################################################
  ####                           Ouput                                       ###
  ##############################################################################
  slot(estimated_result, "simulation_time_memory") <- list("zinbwave" = list("estimation_time" = simulate_detection$Elapsed_Time_sec,
                                                                             "estimation_memory" = simulate_detection$Peak_RAM_Used_MiB))
  slot(estimated_result, "simulation_result") <- list("zinbwave" = simulate_result)
  slot(estimated_result, "simulation_parameters") <- list("zinbwave" = parameters)
  return(estimated_result)
}
